 const types = {
   IS_OPEN_SHOOPING_CARD: "IS_OPEN_SHOOPING_CARD",
   IS_CLOSE_SHOOPING_CARD: "IS_CLOSE_SHOOPING_CARD",
   IS_OPEN_MENU_FILTER: "IS_OPEN_MENU_FILTER",
   IS_CLOSE_MENU_FILTER: "IS_CLOSE_MENU_FILTER",
   IS_OPEN_PROFILE_USER: "IS_OPEN_PROFILE_USER",
   IS_CLOSE_PROFILE_USER: "IS_CLOSE_PROFILE_USER",
 }; 

 export default types;